**IMPORT THE PYTHON PACKAGES**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

**READ THE DATASET USING PANDAS**

In [ ]:
import pandas as pd
data = pd.read_csv("/content/spam.csv", encoding='ISO-8859-1')
print(data.head())



     v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN  


In [ ]:
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [ ]:
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

**CHECK THE NULL VALUES**

In [ ]:
data.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

**Remove Rows/Columns with Null Values**

In [ ]:
data = data.dropna()
data = data.dropna(axis=1)

**Impute Null Values**

In [ ]:
data.fillna(data.mean(), inplace=True)

<ipython-input-7-a20208f658ce>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.fillna(data.mean(), inplace=True)


**Forward or Backward Fill**

In [ ]:
data = data.ffill()
data = data.bfill()

**Interpolation**

In [ ]:
import pandas as pd
# Assuming 'column_name' is the column you want to interpolate and convert to numeric
data['Unnamed: 2'] = pd.to_numeric(data['Unnamed: 2'], errors='coerce')
# Now, you can apply the interpolation
data.interpolate(method='linear', inplace=True)


**AFTER CLEAR THE NULL VALUES CHECK THE ANY NULL VALUES OR THERER**

# **1.DataPreprocessing**

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

# Sample DataFrame with a column containing string values (e.g., text reviews)

In [ ]:
data =  pd.read_csv("/content/spam.csv", encoding='ISO-8859-1')
df = pd.DataFrame(data)

**1. Lowercasing**

In [ ]:
df['v1'] = df['v1'].str.lower()

**2. Removing Punctuation**

In [ ]:
import string
df['v1'] = df['v1'].apply(lambda x: ''.join([char for char in x if char not in string.punctuation]))

**NLTLK DOWNLOAD**

In [ ]:
import nltk
from nltk.tokenize import word_tokenize

# Download the 'punkt' resource
nltk.download('punkt')

# Assuming df is your DataFrame
df['v1'] = df['v1'].apply(word_tokenize)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


**3.Tokenization**

In [ ]:
from nltk.tokenize import word_tokenize
df['v1'] = df['v1'].apply(str)
df['v1'] = df['v1'].apply(word_tokenize)

In [ ]:
!pip install nltk
!nltk.download punkt

/bin/bash: line 1: nltk.download: command not found


**DOWNLOAD A STOPWORDS RESOURCES**

In [ ]:
import nltk
# Download the 'stopwords' resource
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

**4. Removing Stopword**

In [ ]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
df['v1'] = df['v1'].apply(lambda x: [word for word in x if word not in stop_words])


**5. Stemming or Lemmatization**

In [ ]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

**DOWNLOAD WORDNET RESOURCE**

In [ ]:
import nltk
# Download the 'Wordnet' resource
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

**Using lemmatization in this example**

In [ ]:
lemmatizer = WordNetLemmatizer()
df['v1'] = df['v1'].apply(lambda x: [lemmatizer.lemmatize(word) for word in x])

**6. Splitting into Training and Validation Sets**

In [ ]:
X_train, X_val = train_test_split(df['v1'], test_size=0.2, random_state=42)

**7. Vectorization**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
X_train_text = [' '.join(text) for text in X_train]
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train_text)
X_val_text = [' '.join(text) for text in X_val]
X_val_tfidf = vectorizer.transform(X_val_text)

**DISPLAY THE PROCESSED DATA**

In [ ]:
print("Processed Training Data:")
print(X_train_tfidf.toarray())
print("\nProcessed Validation Data:")
print(X_val_tfidf.toarray())

Processed Training Data:
[[1. 0.]
 [0. 1.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]

Processed Validation Data:
[[1. 0.]
 [1. 0.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [0. 1.]]


# **2.Feature Engineering**

**i. Word Count Feature**

In [ ]:
df['word_count'] = df['v1'].apply(lambda x: len(str(x).split()))

**ii. Character Count Feature**

In [ ]:
df['char_count'] = df['v1'].apply(lambda x: len(str(x)))

**iii. Average Word Length Feature**

In [ ]:
df['avg_word_length'] = df['char_count'] / df['word_count']

**iv.Presence of Numeric Digits Feature**

In [ ]:
df['has_digits'] = df['v1'].apply(lambda x: any(char.isdigit() for char in x))

**V. TF-IDF Vectorization**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
df['v1'] = df['v1'].apply(lambda x: ' '.join(x))
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(df['v1'])
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())
df = pd.concat([df, tfidf_df], axis=1)


**Vi. Display the DataFrame with new features**

In [ ]:
print("DataFrame with New Features:")
print(df)

DataFrame with New Features:
               v1                                                 v2  \
0      [ 'ham ' ]  Go until jurong point, crazy.. Available only ...   
1      [ 'ham ' ]                      Ok lar... Joking wif u oni...   
2     [ 'spam ' ]  Free entry in 2 a wkly comp to win FA Cup fina...   
3      [ 'ham ' ]  U dun say so early hor... U c already then say...   
4      [ 'ham ' ]  Nah I don't think he goes to usf, he lives aro...   
...           ...                                                ...   
5567  [ 'spam ' ]  This is the 2nd time we have tried 2 contact u...   
5568   [ 'ham ' ]              Will Ì_ b going to esplanade fr home?   
5569   [ 'ham ' ]  Pity, * was in mood for that. So...any other s...   
5570   [ 'ham ' ]  The guy did some bitching but I acted like i'd...   
5571   [ 'ham ' ]                         Rofl. Its true to its name   

     Unnamed: 2 Unnamed: 3 Unnamed: 4  word_count  char_count  \
0           NaN        NaN        NaN    

# **3.Model Selection**

**i. import the packages**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

**ii. Sample DataFrame with a column containing string values (e.g., text reviews) and labels**

In [ ]:
import pandas as pd

# Load your dataset
data = pd.read_csv("/content/spam.csv", encoding='ISO-8859-1')

# Create an empty list to store labels
labels = []

# Iterate over rows in the dataset and assign labels based on conditions
for index, row in data.iterrows():
    # Example: Assuming a column named 'v1' is used for labeling based on categories
    if row['v1'] == 'ham':
        labels.append(0)
    elif row['v1'] == 'spam':
        labels.append(1)
    else:
        labels.append(-1)  # or another value for other cases

# Add the labels to the dataset
data['label'] = labels

# Save the labeled dataset to a new CSV file
data.to_csv("labeled_dataset.csv", index=False)
print(data)


        v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  label  
0           NaN        NaN      0  
1           NaN

**ii. TF-IDF Vectorization**

In [ ]:
vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(df['v1'])
y = df['v1']

**iii. Splitting into Training and Validation Sets**

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)

**iv.Model Selection Random Forest Classifier in this example**

In [ ]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

**V. Model Evaluation on Validation Set**

In [ ]:
predictions = model.predict(X_val)
accuracy = accuracy_score(y_val, predictions)
print(f'Validation Accuracy: {accuracy}')

Validation Accuracy: 1.0


In [ ]:
# Evaluate the RandomForestClassifier on the validation set
accuracy = model.score(X_val, y_val)
print(f'Validation Accuracy: {accuracy*100:.2f}%')


Validation Accuracy: 100.00%


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

# Make predictions on validation set
y_pred = model.predict(X_val)

# Create a confusion matrix
cm = confusion_matrix(y_val, y_pred)
print("Confusion Matrix:")
print(cm)

# Classification Report
print("\nClassification Report:")
print(classification_report(y_val, y_pred))


Confusion Matrix:
[[965   0]
 [  0 150]]

Classification Report:
              precision    recall  f1-score   support

  [ 'ham ' ]       1.00      1.00      1.00       965
 [ 'spam ' ]       1.00      1.00      1.00       150

    accuracy                           1.00      1115
   macro avg       1.00      1.00      1.00      1115
weighted avg       1.00      1.00      1.00      1115



In [ ]:
if isinstance(model, RandomForestClassifier):  # Check if the model is RandomForestClassifier
    # Display feature importance
    feature_importance = model.feature_importances_
    print("\nFeature Importance:")
    for feature, importance in zip(df.columns, feature_importance):
        print(f"{feature}: {importance}")



Feature Importance:
v1: 0.48
v2: 0.52
